alderaan = Planet.create(:name => 'Alderaan' , :credits =>  1800 )
bespin = Planet.create(:name => 'Bespin' , :credits =>  1800 )
bothauwi = Planet.create(:name => 'Bothauwi' , :credits =>  1600 )
byss = Planet.create(:name => 'Byss' , :credits =>  1200 )
corellia = Planet.create(:name => 'Corellia' , :credits =>  2400 )
coruscant = Planet.create(:name => 'Coruscant' , :credits =>  2000 )
dagobah = Planet.create(:name => 'Dagobah' , :credits =>  1600 )
dantooine = Planet.create(:name => 'Dantooine' , :credits =>  1400 )
endor = Planet.create(:name => 'Endor' , :credits =>  1400 )
eriadu = Planet.create(:name => 'Eriadu' , :credits =>  2000 )
felucia = Planet.create(:name => 'Felucia' , :credits =>  1600 )
geonosis = Planet.create(:name => 'Geonosis' , :credits =>  1600 )
hoth = Planet.create(:name => 'Hoth' , :credits =>  1800 )
ilum = Planet.create(:name => 'Ilum' , :credits =>  1400 )
kamino = Planet.create(:name => 'Kamino' , :credits =>  1200 )
kashyyyk = Planet.create(:name => 'Kashyyyk' , :credits =>  1600 )
kuat = Planet.create(:name => 'Kuat' , :credits =>  1600 )
mandalore = Planet.create(:name => 'Mandalore' , :credits =>  1600 )
moncalamari = Planet.create(:name => 'Mon Calamari' , :credits =>  1200 )
mustafar = Planet.create(:name => 'Mustafar' , :credits =>  1600 )
mygeeto = Planet.create(:name => 'Mygeeto' , :credits =>  1800 )
naboo = Planet.create(:name => 'Naboo' , :credits =>  1800 )
narshaddaa = Planet.create(:name => 'Nar Shaddaa' , :credits =>  1600 )
polismassa = Planet.create(:name => 'Polis Massa' , :credits =>  1400 )
ryloth = Planet.create(:name => 'Ryloth' , :credits =>  1200 )
tatooine = Planet.create(:name => 'Tatooine' , :credits =>  1800 )
utapau = Planet.create(:name => 'Utapau' , :credits =>  1200 )
yavin = Planet.create(:name => 'Yavin' , :credits =>  1600 )

Route.create(:vector_a => mustafar, :vector_b => polismassa, :distance => 1)
Route.create(:vector_a => hoth, :vector_b => polismassa, :distance => 1)
Route.create(:vector_a => eriadu, :vector_b => mustafar, :distance => 1)
Route.create(:vector_a => dagobah, :vector_b => mustafar, :distance => 1)
Route.create(:vector_a => dagobah, :vector_b => utapau, :distance => 1)
Route.create(:vector_a => dagobah, :vector_b => eriadu, :distance => 1)
Route.create(:vector_a => eriadu, :vector_b => hoth, :distance => 1)
Route.create(:vector_a => endor, :vector_b => hoth, :distance => 1)
Route.create(:vector_a => bespin, :vector_b => hoth, :distance => 1)
Route.create(:vector_a => bespin, :vector_b => endor, :distance => 1)
Route.create(:vector_a => eriadu, :vector_b => naboo, :distance => 1)
Route.create(:vector_a => bespin, :vector_b => eriadu, :distance => 1)
Route.create(:vector_a => geonosis, :vector_b => naboo, :distance => 1)
Route.create(:vector_a => geonosis, :vector_b => ryloth, :distance => 1)
Route.create(:vector_a => geonosis, :vector_b => tatooine, :distance => 1)
Route.create(:vector_a => naboo, :vector_b => tatooine, :distance => 1)
Route.create(:vector_a => corellia, :vector_b => naboo, :distance => 1)
Route.create(:vector_a => corellia, :vector_b => tatooine, :distance => 1)
Route.create(:vector_a => bothauwi, :vector_b => tatooine, :distance => 1)
Route.create(:vector_a => bespin, :vector_b => corellia, :distance => 1)
Route.create(:vector_a => bothauwi, :vector_b => corellia, :distance => 1)
Route.create(:vector_a => bothauwi, :vector_b => narshaddaa, :distance => 1)
Route.create(:vector_a => kamino, :vector_b => narshaddaa, :distance => 1)
Route.create(:vector_a => kashyyyk, :vector_b => narshaddaa, :distance => 1)
Route.create(:vector_a => corellia, :vector_b => kuat, :distance => 1)
Route.create(:vector_a => corellia, :vector_b => kuat, :distance => 1)
Route.create(:vector_a => alderaan, :vector_b => corellia, :distance => 1)
Route.create(:vector_a => corellia, :vector_b => coruscant, :distance => 1)
Route.create(:vector_a => kashyyyk, :vector_b => kuat, :distance => 1)
Route.create(:vector_a => byss, :vector_b => coruscant, :distance => 1)
Route.create(:vector_a => alderaan, :vector_b => coruscant, :distance => 1)
Route.create(:vector_a => coruscant, :vector_b => ilum, :distance => 1)
Route.create(:vector_a => coruscant, :vector_b => mygeeto, :distance => 1)
Route.create(:vector_a => ilum, :vector_b => mygeeto, :distance => 1)
Route.create(:vector_a => alderaan, :vector_b => mandalore, :distance => 1)
Route.create(:vector_a => mandalore, :vector_b => mygeeto, :distance => 1)
Route.create(:vector_a => dantooine, :vector_b => mygeeto, :distance => 1)
Route.create(:vector_a => dantooine, :vector_b => yavin, :distance => 1)
Route.create(:vector_a => mandalore, :vector_b => yavin, :distance => 1)
Route.create(:vector_a => felucia, :vector_b => yavin, :distance => 1)
Route.create(:vector_a => felucia, :vector_b => kashyyyk, :distance => 1)
Route.create(:vector_a => felucia, :vector_b => moncalamari, :distance => 1)

Unit.create(:name => 'X-Wing', :price => 275 )
Unit.create(:name => 'Y-Wing', :price => 250 )
Unit.create(:name => 'A-Wing', :price => 350 )
Unit.create(:name => 'B-Wing', :price => 500 )
Unit.create(:name => 'T-Wing', :price => 140 )
Unit.create(:name => 'Z-95', :price => 140 )
Unit.create(:name => 'Skipray Blastboat', :price => 400 )
Unit.create(:name => 'R-41 Starchaser', :price => 200 )
Unit.create(:name => 'Firespray', :price => 325 )
Unit.create(:name => 'Pursuer', :price => 250 )
Unit.create(:name => 'Cloackshape Fighter', :price => 200 )
Unit.create(:name => 'Razor Fighter', :price => 250 )
Unit.create(:name => 'Planetary Fighter', :price => 200 )
Unit.create(:name => 'Supa Fighter', :price => 250 )
Unit.create(:name => 'Pinook Fighter', :price => 120 )
Unit.create(:name => 'Preybird Fighter', :price => 150 )
Unit.create(:name => 'Tie Fighter', :price => 75 )
Unit.create(:name => 'Tie Bomber', :price => 100 )
Unit.create(:name => 'Tie Interceptor', :price => 100 )
Unit.create(:name => 'Tie Advanced', :price => 400 )
Unit.create(:name => 'Tie Defender', :price => 1250 )
Unit.create(:name => 'Toscan Fighter', :price => 300 )
Unit.create(:name => 'Missile Boat', :price => 1250 )
Unit.create(:name => 'Assault Gunboat', :price => 450 )
Unit.create(:name => 'Authority IRD', :price => 125 )

Unit.create(:name => 'YT-1300', :price => 400 )
Unit.create(:name => 'YT-2000', :price => 1200 )
Unit.create(:name => 'Millenium Falcon', :price => 1000 )
Unit.create(:name => 'Assault Transport', :price => 800 )
Unit.create(:name => 'Escort Transport', :price => 900 )
Unit.create(:name => 'Escort Shuttle', :price => 350 )
Unit.create(:name => 'Scout Craft', :price => 500 )
Unit.create(:name => 'Shuttle', :price => 250 )
Unit.create(:name => 'Stormtrooper Transport', :price => 250 )
Unit.create(:name => 'System Patrol Craft', :price => 1100 )
Unit.create(:name => 'Assault Shuttle', :price => 750 )

Unit.create(:name => 'Calamari Cruiser', :price => 7200 )
Unit.create(:name => 'Lt Calamari Cruiser', :price => 3000 )
Unit.create(:name => 'Calamari Cruiser II', :price => 7200 )
Unit.create(:name => 'Assault Frigate', :price => 5600 )
Unit.create(:name => 'Mod Corvette', :price => 1200 )
Unit.create(:name => 'Marauder Corvette', :price => 2750 )
Unit.create(:name => 'Dreadnaught', :price => 3800 )
Unit.create(:name => 'Bulk Cruiser', :price => 3200 )
Unit.create(:name => 'Lancer Frigate', :price => 1600 )
Unit.create(:name => 'Corellian Gunship', :price => 1200 )
Unit.create(:name => 'Corellian Corvette', :price => 1200 )
Unit.create(:name => 'Mod Neb B Frigate', :price => 2400 )
Unit.create(:name => 'Nebulon B Frigate', :price => 1600 )
Unit.create(:name => 'Strike Cruiser', :price => 2500 )
Unit.create(:name => 'Escort Carrier', :price => 2500 )
Unit.create(:name => 'Interdictor', :price => 7000 )
Unit.create(:name => 'Victory Star Destroyer', :price => 7500 )
Unit.create(:name => 'Victory Star Destroyer II', :price => 8200 )
Unit.create(:name => 'Imperial Star Destroyer', :price => 8900 )
Unit.create(:name => 'Imperial Star Destroyer II', :price => 9500 )
Unit.create(:name => 'Super Star Destroyer', :price => 50000 )

Unit.create(:name => 'Mag Pulse Torpedo', :price => 350 )
Unit.create(:name => 'Ion Pulse Torpedo', :price => 200 )
Unit.create(:name => 'Concussion Missile', :price => 100 )
Unit.create(:name => 'Proton Torpedo', :price => 150 )
Unit.create(:name => 'Adv Missile', :price => 300 )
Unit.create(:name => 'Adv Torpedo', :price => 400 )
Unit.create(:name => 'Heavy Rocket', :price => 800 )
Unit.create(:name => 'Space Bomb', :price => 1000 )

Unit.create(:name => 'Chaff', :price => 25 )
Unit.create(:name => 'Flare', :price => 125 )

Facility.create(:name => 'Factory', :price => 5000 )
Facility.create(:name => 'Industrial Complex', :price => 2000 )
Facility.create(:name => 'Shipyard', :price => 7500 )

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
    
