Planet.create(:name => 'Alderaan' , :credits =>  1800 )
Planet.create(:name => 'Bespin' , :credits =>  1800 )
Planet.create(:name => 'Bothauwi' , :credits =>  1600 )
Planet.create(:name => 'Byss' , :credits =>  1200 )
Planet.create(:name => 'Corellia' , :credits =>  2400 )
Planet.create(:name => 'Coruscant' , :credits =>  2000 )
Planet.create(:name => 'Dagobah' , :credits =>  1600 )
Planet.create(:name => 'Dantooine' , :credits =>  1400 )
Planet.create(:name => 'Endor' , :credits =>  1400 )
Planet.create(:name => 'Eriadu' , :credits =>  2000 )
Planet.create(:name => 'Felucia' , :credits =>  1600 )
Planet.create(:name => 'Geonosis' , :credits =>  1600 )
Planet.create(:name => 'Hoth' , :credits =>  1800 )
Planet.create(:name => 'Ilum' , :credits =>  1400 )
Planet.create(:name => 'Kamino' , :credits =>  1200 )
Planet.create(:name => 'Kashyyyk' , :credits =>  1600 )
Planet.create(:name => 'Kuat' , :credits =>  1600 )
Planet.create(:name => 'Mandalore' , :credits =>  1600 )
Planet.create(:name => 'Mon Calamari' , :credits =>  1200 )
Planet.create(:name => 'Mustafar' , :credits =>  1600 )
Planet.create(:name => 'Mygeeto' , :credits =>  1800 )
Planet.create(:name => 'Naboo' , :credits =>  1800 )
Planet.create(:name => 'Nar Shaddaa' , :credits =>  1600 )
Planet.create(:name => 'Polis Massa' , :credits =>  1400 )
Planet.create(:name => 'Ryloth' , :credits =>  1200 )
Planet.create(:name => 'Tatooine' , :credits =>  1800 )
Planet.create(:name => 'Utapau' , :credits =>  1200 )
Planet.create(:name => 'Yavin' , :credits =>  1600 )

Route.create(:vector_a => 20, :vector_b => 24, :distance => 1)
Route.create(:vector_a => 13, :vector_b => 24, :distance => 1)
Route.create(:vector_a => 10, :vector_b => 20, :distance => 1)
Route.create(:vector_a => 7, :vector_b => 20, :distance => 1)
Route.create(:vector_a => 7, :vector_b => 27, :distance => 1)
Route.create(:vector_a => 7, :vector_b => 10, :distance => 1)
Route.create(:vector_a => 10, :vector_b => 13, :distance => 1)
Route.create(:vector_a => 9, :vector_b => 13, :distance => 1)
Route.create(:vector_a => 2, :vector_b => 13, :distance => 1)
Route.create(:vector_a => 2, :vector_b => 9, :distance => 1)
Route.create(:vector_a => 10, :vector_b => 22, :distance => 1)
Route.create(:vector_a => 2, :vector_b => 10, :distance => 1)
Route.create(:vector_a => 12, :vector_b => 22, :distance => 1)
Route.create(:vector_a => 12, :vector_b => 25, :distance => 1)
Route.create(:vector_a => 12, :vector_b => 26, :distance => 1)
Route.create(:vector_a => 22, :vector_b => 26, :distance => 1)
Route.create(:vector_a => 5, :vector_b => 22, :distance => 1)
Route.create(:vector_a => 5, :vector_b => 26, :distance => 1)
Route.create(:vector_a => 3, :vector_b => 26, :distance => 1)
Route.create(:vector_a => 2, :vector_b => 5, :distance => 1)
Route.create(:vector_a => 3, :vector_b => 5, :distance => 1)
Route.create(:vector_a => 3, :vector_b => 23, :distance => 1)
Route.create(:vector_a => 15, :vector_b => 23, :distance => 1)
Route.create(:vector_a => 16, :vector_b => 23, :distance => 1)
Route.create(:vector_a => 99, :vector_b => 99, :distance => 1)
Route.create(:vector_a => 5, :vector_b => 17, :distance => 1)
Route.create(:vector_a => 1, :vector_b => 5, :distance => 1)
Route.create(:vector_a => 5, :vector_b => 6, :distance => 1)
Route.create(:vector_a => 16, :vector_b => 17, :distance => 1)
Route.create(:vector_a => 4, :vector_b => 6, :distance => 1)
Route.create(:vector_a => 1, :vector_b => 6, :distance => 1)
Route.create(:vector_a => 6, :vector_b => 14, :distance => 1)
Route.create(:vector_a => 6, :vector_b => 21, :distance => 1)
Route.create(:vector_a => 14, :vector_b => 21, :distance => 1)
Route.create(:vector_a => 1, :vector_b => 18, :distance => 1)
Route.create(:vector_a => 18, :vector_b => 21, :distance => 1)
Route.create(:vector_a => 8, :vector_b => 21, :distance => 1)
Route.create(:vector_a => 8, :vector_b => 28, :distance => 1)
Route.create(:vector_a => 18, :vector_b => 28, :distance => 1)
Route.create(:vector_a => 11, :vector_b => 28, :distance => 1)
Route.create(:vector_a => 11, :vector_b => 16, :distance => 1)
Route.create(:vector_a => 11, :vector_b => 19, :distance => 1)

Unit.create(:name => 'X-Wing', :price => 275 )
Unit.create(:name => 'Y-Wing', :price => 250 )
Unit.create(:name => 'A-Wing', :price => 350 )
Unit.create(:name => 'B-Wing', :price => 500 )
Unit.create(:name => 'T-Wing', :price => 140 )
Unit.create(:name => 'Z-95', :price => 140 )
Unit.create(:name => 'Skipray Blastboat', :price => 400 )
Unit.create(:name => 'R-41 Starchaser', :price => 200 )
Unit.create(:name => 'Firespray', :price => 325 )
Unit.create(:name => 'Pursuer', :price => 250 )
Unit.create(:name => 'Cloackshape Fighter', :price => 200 )
Unit.create(:name => 'Razor Fighter', :price => 250 )
Unit.create(:name => 'Planetary Fighter', :price => 200 )
Unit.create(:name => 'Supa Fighter', :price => 250 )
Unit.create(:name => 'Pinook Fighter', :price => 120 )
Unit.create(:name => 'Preybird Fighter', :price => 150 )
Unit.create(:name => 'Tie Fighter', :price => 75 )
Unit.create(:name => 'Tie Bomber', :price => 100 )
Unit.create(:name => 'Tie Interceptor', :price => 100 )
Unit.create(:name => 'Tie Advanced', :price => 400 )
Unit.create(:name => 'Tie Defender', :price => 1250 )
Unit.create(:name => 'Toscan Fighter', :price => 300 )
Unit.create(:name => 'Missile Boat', :price => 1250 )
Unit.create(:name => 'Assault Gunboat', :price => 450 )
Unit.create(:name => 'Authority IRD', :price => 125 )

Unit.create(:name => 'YT-1300', :price => 400 )
Unit.create(:name => 'YT-2000', :price => 1200 )
Unit.create(:name => 'Millenium Falcon', :price => 1000 )
Unit.create(:name => 'Assault Transport', :price => 800 )
Unit.create(:name => 'Escort Transport', :price => 900 )
Unit.create(:name => 'Escort Shuttle', :price => 350 )
Unit.create(:name => 'Scout Craft', :price => 500 )
Unit.create(:name => 'Shuttle', :price => 250 )
Unit.create(:name => 'Stormtrooper Transport', :price => 250 )
Unit.create(:name => 'System Patrol Craft', :price => 1100 )
Unit.create(:name => 'Assault Shuttle', :price => 750 )

Unit.create(:name => 'Calamari Cruiser', :price => 7200 )
Unit.create(:name => 'Lt Calamari Cruiser', :price => 3000 )
Unit.create(:name => 'Calamari Cruiser II', :price => 7200 )
Unit.create(:name => 'Assault Frigate', :price => 5600 )
Unit.create(:name => 'Mod Corvette', :price => 1200 )
Unit.create(:name => 'Marauder Corvette', :price => 2750 )
Unit.create(:name => 'Dreadnaught', :price => 3800 )
Unit.create(:name => 'Bulk Cruiser', :price => 3200 )
Unit.create(:name => 'Lancer Frigate', :price => 1600 )
Unit.create(:name => 'Corellian Gunship', :price => 1200 )
Unit.create(:name => 'Corellian Corvette', :price => 1200 )
Unit.create(:name => 'Mod Neb B Frigate', :price => 2400 )
Unit.create(:name => 'Nebulon B Frigate', :price => 1600 )
Unit.create(:name => 'Strike Cruiser', :price => 2500 )
Unit.create(:name => 'Escort Carrier', :price => 2500 )
Unit.create(:name => 'Interdictor', :price => 7000 )
Unit.create(:name => 'Victory Star Destroyer', :price => 7500 )
Unit.create(:name => 'Victory Star Destroyer II', :price => 8200 )
Unit.create(:name => 'Imperial Star Destroyer', :price => 8900 )
Unit.create(:name => 'Imperial Star Destroyer II', :price => 9500 )
Unit.create(:name => 'Super Star Destroyer', :price => 50000 )

Unit.create(:name => 'Mag Pulse Torpedo', :price => 350 )
Unit.create(:name => 'Ion Pulse Torpedo', :price => 200 )
Unit.create(:name => 'Concussion Missile', :price => 100 )
Unit.create(:name => 'Proton Torpedo', :price => 150 )
Unit.create(:name => 'Adv Missile', :price => 300 )
Unit.create(:name => 'Adv Torpedo', :price => 400 )
Unit.create(:name => 'Heavy Rocket', :price => 800 )
Unit.create(:name => 'Space Bomb', :price => 1000 )

Unit.create(:name => 'Chaff', :price => 25 )
Unit.create(:name => 'Flare', :price => 125 )

Facility.create(:name => 'Factory', :price => 5000 )
Facility.create(:name => 'Industrial Complex', :price => 2000 )
Facility.create(:name => 'Shipyard', :price => 8000 )

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
    
